Issue/2298 add cache at policy level
gravitee-io/gravitee-ui-components pull request #283
Opened 2021-02-19 18:38 UTC by gcusnieux

fix gravitee-io/issues#2298

2021-02-24 07:41 UTC, phiz71 requested changes

2021-02-24 07:41 UTC, phiz71 commented on stories/atoms/gv-autocomplete.stories.js
> +      innerHTML: '<gv-input placeholder="Type something..." description="Try to ype something"></gv-input>',
```suggestion
      innerHTML: '<gv-input placeholder="Type something..." description="Try to type something"></gv-input>',
```

2021-02-25 08:16 UTC, phiz71 approved these changes

2021-02-25 13:25 UTC, ytvnr requested changes
some typos

2021-02-25 13:25 UTC, ytvnr commented on src/atoms/gv-input.js
> + * @attr {String} description - an description
```suggestion
 * @attr {String} description - a description
```

2021-02-25 13:25 UTC, ytvnr commented on src/atoms/gv-select.js
> + * @attr {String} description - an description
```suggestion
 * @attr {String} description - a description
```

2021-02-25 13:25 UTC, ytvnr commented on src/molecules/gv-expression-language.js
> + * @attr {String} description - an description
```suggestion
 * @attr {String} description - a description
```

2021-02-26 12:41 UTC, ytvnr approved these changes
just a typo in a comment

2021-02-26 12:41 UTC, ytvnr commented on src/atoms/gv-autocomplete.js
> +    // Important when use custom HTML in options
```suggestion
    // Important when using custom HTML in options
```

2021-02-26 13:36 UTC, merged

2021-02-26 13:39 UTC, graviteeio commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@gravitee/ui-components/v/1.2.0)
- [GitHub release](https://github.com/gravitee-io/gravitee-ui-components/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: