Issues/#4894 notifications periods
gravitee-io/gravitee-ui-components pull request #334
Opened 2021-04-29 19:01 UTC by gcusnieux

2021-04-30 06:39 UTC, aelamrani requested changes
Time is not well updated in the input.

![Apr-30-2021 08-37-49](https://user-images.githubusercontent.com/1580262/116657924-831c0080-a98f-11eb-8051-51e5b933fe16.gif)

2021-04-30 12:54 UTC, gaetanmaisse commented on stories/lib/utils.test.js
> +  test('should compare string arrays', () => {
`string arrays` -> 🔍 in the test we are using number arrays

2021-04-30 12:54 UTC, gaetanmaisse commented on stories/lib/utils.test.js
> +  test('should compare string arrays without order', () => {
`string arrays` -> 🔍 in the test we are using number arrays

2021-04-30 12:54 UTC, gaetanmaisse commented on src/molecules/gv-row-expandable.js
> + * @attr {Boolean} only-summary - When true, only summary is clickable for toggle row
`only-summary` isn't straight forward to understand maybe we should rename it with something with the opposite meaning: Collapse on details clicked --- When false, only summary is clickable to collapse the row

But I didn't find an easy name 😞

2021-04-30 12:54 UTC, gaetanmaisse commented on src/molecules/gv-row-expandable.js
> +    }
It is causing troubles when set to true, a click on the `summary` slot is filtered too

2021-05-03 06:22 UTC, jgiovaresco approved these changes
LGTM

2021-05-05 06:04 UTC, aelamrani approved these changes

2021-05-11 08:32 UTC, merged

2021-05-11 08:37 UTC, graviteeio commented
:tada: This PR is included in version 2.7.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@gravitee/ui-components/v/2.7.0)
- [GitHub release](https://github.com/gravitee-io/gravitee-ui-components/releases/tag/v2.7.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: